# 指定系统
dist: bionic

language: php
php:
  - '7.3'

cache:
  directories:
    - vendor

# 指定源码分支
branches:
  only:
    - master    

before_install:
  - openssl aes-256-cbc -K $encrypted_2d17a8a7ada5_key -iv $encrypted_2d17a8a7ada5_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

# Start: Build Lifecycle
install:
  - composer install --no-dev

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: rsync -azv ./dist/ $DEPLOY_USER@$SERVER:$DEPLOY_DIR/ --delete
#   on:
#     branch: master
